version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
      - SESSION_SECRET=secreto
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mabravo153
      - MONGO_INITDB_ROOT_PASSWORD=contrasenaEjemplo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
