version: "3.9"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=mabravo153
      - MONGO_PASSWORD=contrasenaEjemplo
    command: node app.js
