version: "3.9"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mabravo153
      - MONGO_INITDB_ROOT_PASSWORD=contrasenaEjemplo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
